eureka:
  client:
    serviceUrl:
      defaultZone: http://api-gateway-sr:8761/eureka/
server:
  port: 9092
spring:
  application:
    name: Employee
  data:
    mongodb:
      uri: mongodb+srv://rdchethan22:Chethan22@cluster0.qpqfg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: Employee